owner: ihatenodejs
repo: monitor
sites:
  - name: Main Website
    url: https://www.aidxn.cc
  - name: LibreCloud
    url: https://librecloud.cc
  - name: LibreCloud Webmail
    url: https://mail.librecloud.cc
  - name: LibreCloud Pass (Vaultwarden)
    url: https://pass.librecloud.cc
  - name: LibreCloud Authentik
    url: https://auth.librecloud.cc
  - name: LibreCloud Gitea
    url: https://git.pontusmail.org
  - name: Alt Main Website
    url: https://aidxn.fun
  - name: aidxnFUNretro
    url: https://old.aidxn.fun
  - name: Disfunction Blog
    url: https://disfunction.blog
  - name: Archive Website
    url: https://p0ntus.com
  - name: Retro Main Website
    url: https://old.aidxn.fun
  - name: modules
    url: https://modules.lol
status-website:
  cname: status.p0ntus.com
  logoUrl: https://raw.githubusercontent.com/ihatenodejs/ihatenodejs/refs/heads/main/aidan.jpeg
  name: p0ntus monitor
  introTitle: "welcome to **p0ntus monitor**"
  introMessage: p0ntus monitor watches the status of several of my services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
